name: Continuous integration

permissions:
  contents: read

on: [pull_request, push]

jobs:
  test:
    name: Test Suite
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Install System Dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y \
            cmake pkg-config libssl-dev git clang curl libc6-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-10-12
      - run: rustup component add rustfmt
      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release --workspace
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --workspace

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: latest
          # --avoid-cfg-tarpaulin prevents this compilation error: 'Error: bitvec: cannot find attribute `skip` in this scope'
          # --forward seems to prevent segfaults from occuring during test execution
          args: "--exclude-files '/test,/mock.rs,/mock/mod.rs,/default_weights.rs,/weights.rs,/ext.rs,/runtime-api/,/benchmarking.rs,parachain/*' --avoid-cfg-tarpaulin --forward --timeout 300"

      - name: Upload code coverage results
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
